//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCertes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CertesWrapper {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CertesWrapper() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCertes.Resources.CertesWrapper", typeof(CertesWrapper).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS Challenge Validation set up, but server sent no DNS Challenge.
        /// </summary>
        internal static string ErrorDNS {
            get {
                return ResourceManager.GetString("ErrorDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Challenge Validation set up, but server sent no HTTP Challenge.
        /// </summary>
        internal static string ErrorHTTP {
            get {
                return ResourceManager.GetString("ErrorHTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiating DNS Validation for.
        /// </summary>
        internal static string InitDNS {
            get {
                return ResourceManager.GetString("InitDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiating HTTP Validation for.
        /// </summary>
        internal static string InitHTTP {
            get {
                return ResourceManager.GetString("InitHTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not validate DNS challenge:.
        /// </summary>
        internal static string NoDNSChallenge {
            get {
                return ResourceManager.GetString("NoDNSChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not validate HTTP challenge:.
        /// </summary>
        internal static string NoHTTPChallenge {
            get {
                return ResourceManager.GetString("NoHTTPChallenge", resourceCulture);
            }
        }
    }
}
