//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCertes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CertificateStorageManager {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CertificateStorageManager() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCertes.Resources.CertificateStorageManager", typeof(CertificateStorageManager).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to extract certificate from PFX: .
        /// </summary>
        internal static string ErrorExtractingPFX {
            get {
                return ResourceManager.GetString("ErrorExtractingPFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to import certificate into Default CSP:.
        /// </summary>
        internal static string ErrorImportingCSP {
            get {
                return ResourceManager.GetString("ErrorImportingCSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to import certificate into KSP {0}: {1}.
        /// </summary>
        internal static string ErrorImportKSPOutMsg {
            get {
                return ResourceManager.GetString("ErrorImportKSPOutMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No certificate to import..
        /// </summary>
        internal static string ErrorNoCertificate {
            get {
                return ResourceManager.GetString("ErrorNoCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not using default CSP: not importing into store..
        /// </summary>
        internal static string NotImportingCSP {
            get {
                return ResourceManager.GetString("NotImportingCSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored certificate with DN {0} into Windows Personal Local Machine store..
        /// </summary>
        internal static string StoreCertificateSubject {
            get {
                return ResourceManager.GetString("StoreCertificateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully imported certificate into KSP.
        /// </summary>
        internal static string SuccessImportKSP {
            get {
                return ResourceManager.GetString("SuccessImportKSP", resourceCulture);
            }
        }
    }
}
