//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCertes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Utils {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Utils() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCertes.Resources.Utils", typeof(Utils).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed files from filesystem:.
        /// </summary>
        internal static string DeletedFiles {
            get {
                return ResourceManager.GetString("DeletedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manages certificate using ACME.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve certificate from store:.
        /// </summary>
        internal static string ErrorCertificate {
            get {
                return ResourceManager.GetString("ErrorCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not execute.
        /// </summary>
        internal static string ErrorExecScript {
            get {
                return ResourceManager.GetString("ErrorExecScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not bind certificate to site.
        /// </summary>
        internal static string ErrorIISBind {
            get {
                return ResourceManager.GetString("ErrorIISBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find IIS site.
        /// </summary>
        internal static string ErrorIISFind {
            get {
                return ResourceManager.GetString("ErrorIISFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not generate new key pair:.
        /// </summary>
        internal static string ErrorKeyPair {
            get {
                return ResourceManager.GetString("ErrorKeyPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create Scheduled Task.
        /// </summary>
        internal static string ErrorTask {
            get {
                return ResourceManager.GetString("ErrorTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read Scheduled Task status: .
        /// </summary>
        internal static string ErrorTaskStatus {
            get {
                return ResourceManager.GetString("ErrorTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed script.
        /// </summary>
        internal static string ExecScript {
            get {
                return ResourceManager.GetString("ExecScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found binding by port for site: {0}. Will update it with cert with serial: {1}..
        /// </summary>
        internal static string IISFoundBindSiteNameSerial {
            get {
                return ResourceManager.GetString("IISFoundBindSiteNameSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find binding, will try to create one on port .
        /// </summary>
        internal static string IISNoFoundBindNewPort {
            get {
                return ResourceManager.GetString("IISNoFoundBindNewPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Task &quot;WinCertes - {0}&quot; created successfully..
        /// </summary>
        internal static string SuccessTask {
            get {
                return ResourceManager.GetString("SuccessTask", resourceCulture);
            }
        }
    }
}
