//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCertes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinCertesForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinCertesForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCertes.Resources.WinCertesForm", typeof(WinCertesForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will attempt to Rebind the Certificate to the IIS Site..
        /// </summary>
        internal static string AttemptRebind {
            get {
                return ResourceManager.GetString("AttemptRebind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind to IIS Site.
        /// </summary>
        internal static string BindIISSite {
            get {
                return ResourceManager.GetString("BindIISSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding Certificate to IIS if required....
        /// </summary>
        internal static string BindingCertificateIIS {
            get {
                return ResourceManager.GetString("BindingCertificateIIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding Certificate to IIS Site....
        /// </summary>
        internal static string BindingCertToIIS {
            get {
                return ResourceManager.GetString("BindingCertToIIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will bind the Certificate on renewal..
        /// </summary>
        internal static string BindOnRenewal {
            get {
                return ResourceManager.GetString("BindOnRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate successfully deleted..
        /// </summary>
        internal static string CertificateDeleted {
            get {
                return ResourceManager.GetString("CertificateDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate has been successfully deleted..
        /// </summary>
        internal static string CertificateHasBeenDeleted {
            get {
                return ResourceManager.GetString("CertificateHasBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate has been successfully issued..
        /// </summary>
        internal static string CertificateHasBeenIssued {
            get {
                return ResourceManager.GetString("CertificateHasBeenIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate has been successfully revoked..
        /// </summary>
        internal static string CertificateHasBeenRevoked {
            get {
                return ResourceManager.GetString("CertificateHasBeenRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate issued..
        /// </summary>
        internal static string CertificateIssued {
            get {
                return ResourceManager.GetString("CertificateIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate successfully revoked..
        /// </summary>
        internal static string CertificateRevoked {
            get {
                return ResourceManager.GetString("CertificateRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate will be bound to IIS Site.
        /// </summary>
        internal static string CertificateWillBeBound {
            get {
                return ResourceManager.GetString("CertificateWillBeBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS Site is required for Challenge Response..
        /// </summary>
        internal static string ChallengeNeedsSite {
            get {
                return ResourceManager.GetString("ChallengeNeedsSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Port.
        /// </summary>
        internal static string CheckPort {
            get {
                return ResourceManager.GetString("CheckPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration:.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to Delete the certificate and reset configuration?.
        /// </summary>
        internal static string ConfirmDeleteCertificate {
            get {
                return ResourceManager.GetString("ConfirmDeleteCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete the Extra Configuration.
        /// </summary>
        internal static string ConfirmDeleteConfiguration {
            get {
                return ResourceManager.GetString("ConfirmDeleteConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Generate a Certificate for the following domains {0} using a service at {1} and registering with the e-mail address {2}..
        /// </summary>
        internal static string ConfirmGenerateCertificateDomainsServiceEmail {
            get {
                return ResourceManager.GetString("ConfirmGenerateCertificateDomainsServiceEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to create a new Extra Configuration:.
        /// </summary>
        internal static string ConfirmNewConfiguration {
            get {
                return ResourceManager.GetString("ConfirmNewConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to Revoke and delete the Certificate?.
        /// </summary>
        internal static string ConfirmRevokeCertificate {
            get {
                return ResourceManager.GetString("ConfirmRevokeCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update the Settings?.
        /// </summary>
        internal static string ConfirmUpdateSettings {
            get {
                return ResourceManager.GetString("ConfirmUpdateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Configuration.
        /// </summary>
        internal static string CreateNewConfiguration {
            get {
                return ResourceManager.GetString("CreateNewConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Scheduled Task....
        /// </summary>
        internal static string CreatingTask {
            get {
                return ResourceManager.GetString("CreatingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Scheduled Task if required....
        /// </summary>
        internal static string CreatingTaskIfRequired {
            get {
                return ResourceManager.GetString("CreatingTaskIfRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days before Renewal Period will be updated to.
        /// </summary>
        internal static string DaysBeforeRenewal {
            get {
                return ResourceManager.GetString("DaysBeforeRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Configuration.
        /// </summary>
        internal static string DefaultConfiguration {
            get {
                return ResourceManager.GetString("DefaultConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Scheduled Task....
        /// </summary>
        internal static string DeletingTask {
            get {
                return ResourceManager.GetString("DeletingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domains*.
        /// </summary>
        internal static string Domains {
            get {
                return ResourceManager.GetString("Domains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domains to generate certificate for are required..
        /// </summary>
        internal static string DomainsRequired {
            get {
                return ResourceManager.GetString("DomainsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail*:.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not register ACME service account with service address: {0} and e-mail address: {1}.
        /// </summary>
        internal static string ErrorACMEServiceEmail {
            get {
                return ResourceManager.GetString("ErrorACMEServiceEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Binding to IIS Site, but certificate generated..
        /// </summary>
        internal static string ErrorBindingCertificateGenerated {
            get {
                return ResourceManager.GetString("ErrorBindingCertificateGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Verify, cleaning up....
        /// </summary>
        internal static string ErrorFailedCleaningUp {
            get {
                return ResourceManager.GetString("ErrorFailedCleaningUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find configuration or configuration does not match Certificate domains..
        /// </summary>
        internal static string ErrorFindCertificate {
            get {
                return ResourceManager.GetString("ErrorFindCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cound not read IIS binding, try resetting IIS, continuing:.
        /// </summary>
        internal static string ErrorGetBinding {
            get {
                return ResourceManager.GetString("ErrorGetBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cound not read IIS binding, try resetting IIS, breaking:.
        /// </summary>
        internal static string ErrorGetBindingFail {
            get {
                return ResourceManager.GetString("ErrorGetBindingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error issuing Certificate..
        /// </summary>
        internal static string ErrorIssuingCertificate {
            get {
                return ResourceManager.GetString("ErrorIssuingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retreive the generated Certificate..
        /// </summary>
        internal static string ErrorRetrievingCertificate {
            get {
                return ResourceManager.GetString("ErrorRetrievingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error revoking certificate, it could already be revoked..
        /// </summary>
        internal static string ErrorRevokingCertificate {
            get {
                return ResourceManager.GetString("ErrorRevokingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify either an HTTP or a DNS validation method..
        /// </summary>
        internal static string ErrorSpecifyHTTPorDNS {
            get {
                return ResourceManager.GetString("ErrorSpecifyHTTPorDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute PowerShell Script:.
        /// </summary>
        internal static string ExecutePS {
            get {
                return ResourceManager.GetString("ExecutePS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing PowerShell Script if required....
        /// </summary>
        internal static string ExecutingPS {
            get {
                return ResourceManager.GetString("ExecutingPS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        internal static string Extra
        {
            get
            {
                return ResourceManager.GetString("Extra", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extra Configuration:.
        /// </summary>
        internal static string ExtraConfiguration {
            get {
                return ResourceManager.GetString("ExtraConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate failed to bind to IIS Site..
        /// </summary>
        internal static string FailedCertBindIIS {
            get {
                return ResourceManager.GetString("FailedCertBindIIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Certificate?.
        /// </summary>
        internal static string GenerateCertificate {
            get {
                return ResourceManager.GetString("GenerateCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domains to Generate certificate for:.
        /// </summary>
        internal static string GenerateDomains {
            get {
                return ResourceManager.GetString("GenerateDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Existing Certificate from Configuration....
        /// </summary>
        internal static string GettingExistingCertificate {
            get {
                return ResourceManager.GetString("GettingExistingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting HTTP Validator....
        /// </summary>
        internal static string GettingHTTPValidator {
            get {
                return ResourceManager.GetString("GettingHTTPValidator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help
        {
            get
            {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WinCertes allows you to generate a free certificate using Lets Encrypt or a service of your choice.
        ///You must start by entering the e-mail address you will be registering the certificate with.
        ///If you are using IIS, simply select the Local IIS Server radio button, now select the IIS Site you will be using for the challenge response and if you wish to bind the certificate after, tick the Bind to IIS Site box. If you are hosting multiple domains, you may want to ensure Server Name Indication is ticked.
        ///If yo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local IIS Server.
        /// </summary>
        internal static string IIS {
            get {
                return ResourceManager.GetString("IIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS Binding SNI Ssl Flag will be updated to.
        /// </summary>
        internal static string IISBindingSNIFlag {
            get {
                return ResourceManager.GetString("IISBindingSNIFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS Site is required to Bind Certificate to..
        /// </summary>
        internal static string IISBindNeedsSite {
            get {
                return ResourceManager.GetString("IISBindNeedsSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS Binding Port will be updated to.
        /// </summary>
        internal static string IISBindPortUpdate {
            get {
                return ResourceManager.GetString("IISBindPortUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS Port to bind to:.
        /// </summary>
        internal static string IISPort {
            get {
                return ResourceManager.GetString("IISPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS Settings.
        /// </summary>
        internal static string IISSettings {
            get {
                return ResourceManager.GetString("IISSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS Site {0} with Web Root at {1} will be used for Challange response at renewal..
        /// </summary>
        internal static string IISSiteAtWebRootRenewal {
            get {
                return ResourceManager.GetString("IISSiteAtWebRootRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IIS Site at {0} will be used for the Challange Response..
        /// </summary>
        internal static string IISSiteChallange {
            get {
                return ResourceManager.GetString("IISSiteChallange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Certes....
        /// </summary>
        internal static string InitCertes {
            get {
                return ResourceManager.GetString("InitCertes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Certificate.
        /// </summary>
        internal static string IssueCertificate {
            get {
                return ResourceManager.GetString("IssueCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Issued Certificate will be binded to the IIS Site {0} on Port {1}.
        /// </summary>
        internal static string IssuedCertificateIISPort {
            get {
                return ResourceManager.GetString("IssuedCertificateIISPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing Certificate....
        /// </summary>
        internal static string IssuingCertificate {
            get {
                return ResourceManager.GetString("IssuingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Configuration.
        /// </summary>
        internal static string NewConfiguration {
            get {
                return ResourceManager.GetString("NewConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Domain:.
        /// </summary>
        internal static string NewDomain {
            get {
                return ResourceManager.GetString("NewDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate not bound to any IIS site.
        /// </summary>
        internal static string NoBindIIS {
            get {
                return ResourceManager.GetString("NoBindIIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate will not be bound to an IIS Site on renewal..
        /// </summary>
        internal static string NoBindOnRenewal {
            get {
                return ResourceManager.GetString("NoBindOnRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;None&gt;.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will not unbind the Certificate from the IIS Site, but will not rebind it on renewal..
        /// </summary>
        internal static string NoRebind {
            get {
                return ResourceManager.GetString("NoRebind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORT {0} IN USE.
        /// </summary>
        internal static string Port0InUse {
            get {
                return ResourceManager.GetString("Port0InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORT IN USE.
        /// </summary>
        internal static string PortInUse {
            get {
                return ResourceManager.GetString("PortInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Core Script.
        /// </summary>
        internal static string PowerShell {
            get {
                return ResourceManager.GetString("PowerShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Execution Policy:.
        /// </summary>
        internal static string PSExecPolicy {
            get {
                return ResourceManager.GetString("PSExecPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting PowerShell Script Execution Policy will be updated to.
        /// </summary>
        internal static string PSExecSetting {
            get {
                return ResourceManager.GetString("PSExecSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Script execution will be updated to.
        /// </summary>
        internal static string PSExecUpdate {
            get {
                return ResourceManager.GetString("PSExecUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Scripts (*.ps1)|*.ps1|All files (*.*)|*.*.
        /// </summary>
        internal static string PSFilter {
            get {
                return ResourceManager.GetString("PSFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Script Execution Policy will be updated to.
        /// </summary>
        internal static string PSScriptExecSetting {
            get {
                return ResourceManager.GetString("PSScriptExecSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Script will be updated to.
        /// </summary>
        internal static string PSScriptUpdate {
            get {
                return ResourceManager.GetString("PSScriptUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PowerShell Script {0} will be executed after successfully issuing and/or binding the certificate.
        /// </summary>
        internal static string PSScriptWillBeExecuted {
            get {
                return ResourceManager.GetString("PSScriptWillBeExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Issue Certificate..
        /// </summary>
        internal static string ReadyIssue {
            get {
                return ResourceManager.GetString("ReadyIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Renew Certificate..
        /// </summary>
        internal static string ReadyRenew {
            get {
                return ResourceManager.GetString("ReadyRenew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Update Settings..
        /// </summary>
        internal static string ReadyUpdate {
            get {
                return ResourceManager.GetString("ReadyUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is recommended to Revoke and Delete the Certificate first..
        /// </summary>
        internal static string RecommendDelete {
            get {
                return ResourceManager.GetString("RecommendDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTERED.
        /// </summary>
        internal static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering New Account....
        /// </summary>
        internal static string RegisteringNewAccount {
            get {
                return ResourceManager.GetString("RegisteringNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering New Order and Verifiying....
        /// </summary>
        internal static string RegisteringNewOrder {
            get {
                return ResourceManager.GetString("RegisteringNewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Certificate from Configuration....
        /// </summary>
        internal static string RemovingCertificate {
            get {
                return ResourceManager.GetString("RemovingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing temporary files....
        /// </summary>
        internal static string RemovingTemp {
            get {
                return ResourceManager.GetString("RemovingTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew Days before Expiration:.
        /// </summary>
        internal static string RenewalDelay {
            get {
                return ResourceManager.GetString("RenewalDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew Certificate.
        /// </summary>
        internal static string RenewCertificate {
            get {
                return ResourceManager.GetString("RenewCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Certificate....
        /// </summary>
        internal static string RetrievingCertificate {
            get {
                return ResourceManager.GetString("RetrievingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke Certificate.
        /// </summary>
        internal static string RevokeCertificate {
            get {
                return ResourceManager.GetString("RevokeCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoking Certificate with ACME Service....
        /// </summary>
        internal static string RevokingCertificate {
            get {
                return ResourceManager.GetString("RevokingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Task.
        /// </summary>
        internal static string ScheduledTask {
            get {
                return ResourceManager.GetString("ScheduledTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule a Task to Renew Automatically.
        /// </summary>
        internal static string ScheduleTaskAuto {
            get {
                return ResourceManager.GetString("ScheduleTaskAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Port:.
        /// </summary>
        internal static string ServerPort {
            get {
                return ResourceManager.GetString("ServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service:.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Updated..
        /// </summary>
        internal static string SettingsUpdated {
            get {
                return ResourceManager.GetString("SettingsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Certificate.
        /// </summary>
        internal static string ShowCertificate {
            get {
                return ResourceManager.GetString("ShowCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Bindings:.
        /// </summary>
        internal static string SiteBindings {
            get {
                return ResourceManager.GetString("SiteBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name Indication.
        /// </summary>
        internal static string SNI {
            get {
                return ResourceManager.GetString("SNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standalone HTTP Server.
        /// </summary>
        internal static string Standalone {
            get {
                return ResourceManager.GetString("Standalone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standalone HTTP Server requires a Port that is Not in Use..
        /// </summary>
        internal static string StandaloneRequiresPort {
            get {
                return ResourceManager.GetString("StandaloneRequiresPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standalone HTTP Server Settings.
        /// </summary>
        internal static string StandaloneSettings {
            get {
                return ResourceManager.GetString("StandaloneSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Standalone HTTP Server on Port {0} will be used for the Challange Response..
        /// </summary>
        internal static string StandaloneUsedResponseOnPort {
            get {
                return ResourceManager.GetString("StandaloneUsedResponseOnPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Challenges are processed on Port 80, if you use a different port above you must set Port Forwarding on your Router accordingly..
        /// </summary>
        internal static string StandaloneWarning {
            get {
                return ResourceManager.GetString("StandaloneWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storing Certificate....
        /// </summary>
        internal static string StoringCertificate {
            get {
                return ResourceManager.GetString("StoringCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully bound certificate for IIS site:.
        /// </summary>
        internal static string SuccessBindIIS {
            get {
                return ResourceManager.GetString("SuccessBindIIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate successfully rebound to IIS Site..
        /// </summary>
        internal static string SuccessCertBoundIIS {
            get {
                return ResourceManager.GetString("SuccessCertBoundIIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Scheduled Task will be created to insure the certificate is renewed within {0} of expiry..
        /// </summary>
        internal static string TaskCreatedDaysBefore {
            get {
                return ResourceManager.GetString("TaskCreatedDaysBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Task will be Scheduled to renew the certificate automatically..
        /// </summary>
        internal static string TaskWillBeCreated {
            get {
                return ResourceManager.GetString("TaskWillBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Scheduled Task will be deleted so the certificate will not be renewed automatically..
        /// </summary>
        internal static string TaskWillBeDeleted {
            get {
                return ResourceManager.GetString("TaskWillBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update IIS Settings.
        /// </summary>
        internal static string UpdateIISSetting {
            get {
                return ResourceManager.GetString("UpdateIISSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Settings.
        /// </summary>
        internal static string UpdateSettings {
            get {
                return ResourceManager.GetString("UpdateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Settings....
        /// </summary>
        internal static string UpdatingSettings {
            get {
                return ResourceManager.GetString("UpdatingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid E-mail is Required..
        /// </summary>
        internal static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Service address is Required..
        /// </summary>
        internal static string ValidService {
            get {
                return ResourceManager.GetString("ValidService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified, cleaning up....
        /// </summary>
        internal static string VerifiedCleaningUp {
            get {
                return ResourceManager.GetString("VerifiedCleaningUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Root for Challange:.
        /// </summary>
        internal static string WebRootChallange {
            get {
                return ResourceManager.GetString("WebRootChallange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinCertes.
        /// </summary>
        internal static string WinCertes {
            get {
                return ResourceManager.GetString("WinCertes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with the Execution Policy set to.
        /// </summary>
        internal static string WithPSExecPolicy {
            get {
                return ResourceManager.GetString("WithPSExecPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with the SNI Ssl Flag on..
        /// </summary>
        internal static string WithSNI {
            get {
                return ResourceManager.GetString("WithSNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing new Configuration....
        /// </summary>
        internal static string WritingConfiguration {
            get {
                return ResourceManager.GetString("WritingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing Settings into Configuration....
        /// </summary>
        internal static string WritingSettings {
            get {
                return ResourceManager.GetString("WritingSettings", resourceCulture);
            }
        }
    }
}
