//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCertes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinCertesOptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinCertesOptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCertes.Resources.WinCertesOptions", typeof(WinCertesOptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dns-01 validation.
        /// </summary>
        internal static string AuthDNS {
            get {
                return ResourceManager.GetString("AuthDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http-01 validation with external web server.
        /// </summary>
        internal static string AuthIIS {
            get {
                return ResourceManager.GetString("AuthIIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth. Mode:.
        /// </summary>
        internal static string AuthMode {
            get {
                return ResourceManager.GetString("AuthMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http-01 validation standalone.
        /// </summary>
        internal static string AuthStandalone {
            get {
                return ResourceManager.GetString("AuthStandalone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current certificate expiration date is: .
        /// </summary>
        internal static string CertificateExpiration {
            get {
                return ResourceManager.GetString("CertificateExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate exists and does not need to be renewed.
        /// </summary>
        internal static string CertificateNotRenewed {
            get {
                return ResourceManager.GetString("CertificateNotRenewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Email: .
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cert Enrolled: .
        /// </summary>
        internal static string Enrolled {
            get {
                return ResourceManager.GetString("Enrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not Read/Write command line parameters to configuration: .
        /// </summary>
        internal static string ErrorReadWrite {
            get {
                return ResourceManager.GetString("ErrorReadWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Threshold Date after delay: .
        /// </summary>
        internal static string ExpirationThreshold {
            get {
                return ResourceManager.GetString("ExpirationThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Configs: .
        /// </summary>
        internal static string ExtraConfigs {
            get {
                return ResourceManager.GetString("ExtraConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Port: .
        /// </summary>
        internal static string HTTPPort {
            get {
                return ResourceManager.GetString("HTTPPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS Bind Name: .
        /// </summary>
        internal static string IISBind {
            get {
                return ResourceManager.GetString("IISBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import in CSP: .
        /// </summary>
        internal static string ImportCSP {
            get {
                return ResourceManager.GetString("ImportCSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinCertes is not configured yet.
        /// </summary>
        internal static string NotConfigured {
            get {
                return ResourceManager.GetString("NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PS Exec Policy:.
        /// </summary>
        internal static string PSExecPolicy {
            get {
                return ResourceManager.GetString("PSExecPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PS Script File:.
        /// </summary>
        internal static string PSScript {
            get {
                return ResourceManager.GetString("PSScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered:.
        /// </summary>
        internal static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Delay:.
        /// </summary>
        internal static string RenewalDelay {
            get {
                return ResourceManager.GetString("RenewalDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service URI:.
        /// </summary>
        internal static string ServiceURI {
            get {
                return ResourceManager.GetString("ServiceURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNI Ssl Flag:.
        /// </summary>
        internal static string SNI {
            get {
                return ResourceManager.GetString("SNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Scheduled:.
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Root:.
        /// </summary>
        internal static string WebRoot {
            get {
                return ResourceManager.GetString("WebRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
